// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA91Cr-suDb3VDBPwLDp_ci6NOkWCKEw7k',
    appId: '1:836227669649:web:b3871de0ec7dbfa49fa930',
    messagingSenderId: '836227669649',
    projectId: 'community-app-81701',
    authDomain: 'community-app-81701.firebaseapp.com',
    storageBucket: 'community-app-81701.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIWAUzdvzTO6ftuT_S3RAgMpIgpvaplP4',
    appId: '1:836227669649:android:f9da318a846fd7f19fa930',
    messagingSenderId: '836227669649',
    projectId: 'community-app-81701',
    storageBucket: 'community-app-81701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3bvGdMXnsMHDDMTnOBDkIDK0ZFcafU_A',
    appId: '1:836227669649:ios:8d7115ec41830f2a9fa930',
    messagingSenderId: '836227669649',
    projectId: 'community-app-81701',
    storageBucket: 'community-app-81701.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3bvGdMXnsMHDDMTnOBDkIDK0ZFcafU_A',
    appId: '1:836227669649:ios:2b32569776278bcf9fa930',
    messagingSenderId: '836227669649',
    projectId: 'community-app-81701',
    storageBucket: 'community-app-81701.appspot.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
